spring.application.name=bikepulse-api
spring.datasource.url=jdbc:mysql://localhost:3306/bikepulse
spring.datasource.username=bikepulse
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8080