spring.application.name=bikepulse-api
spring.datasource.url=${DB_DATASOURCE:jdbc:postgresql://localhost:5432/Bikepulse}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}
server.port=${DB_PORT:8080}